version: 2.1
jobs:
  plan:
    working_directory: ~/work
    docker:
      - image: yushinoda/terraform_npm:latest
    steps:
      - checkout
      - run:
          name: npm install
          command: cd lambda && npm install && cd ..
      - run:
          name: Init terraform
          command: terraform init
      - run:
          name: Validate terraform
          command: terraform validate
      - run:
          name: Plan terraform
          command: terraform plan
  deploy:
    working_directory: ~/work
    docker:
      - image: yushinoda/terraform_npm:latest
    steps:
      - checkout
      - run:
          name: npm install
          command: cd lambda && npm install && cd ..
      - run:
          name: Init terraform
          command: terraform init
      - run:
          name: Apply terraform
          command: terraform apply -auto-approve
workflows:
  version: 2.1
  plan:
    jobs:
      - plan:
          context: aws_yushin0425
          filters:
            branches:
              ignore: release
  deploy:
    jobs:
      - deploy:
          context: aws_yushin0425
          filters:
            branches:
              only: release